name: Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - run: |
          cd main
          npm ci
          npm run build

      - uses: actions/checkout@v3
        with:
          ref: build
          path: build

      - run: |
          rsync -av --recursive --delete ./main/dist ./build/dist
          cp -f ./main/package.json ./build/package.json
          cp -f ./main/package-lock.json ./build/package-lock.json

      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update build files"
          git push
