name: Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: main/package-lock.json

      - run: |
          cd main
          npm ci
          npm run clean
          npm run build

      - uses: actions/checkout@v3
        with:
          ref: build
          path: build

      - run: |
          rm -rf ./build/dist
          rsync -av --recursive --delete ./main/dist ./build
          cp -f ./main/package.json ./build/package.json
          cp -f ./main/package-lock.json ./build/package-lock.json
          echo $(date +%s) > ./build/timestamp.txt

      - run: |
          cd build
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update build files"
          git push

      - run: |
          cd main
          MICROGEN_FUNCTION_DATA="${{ secrets.MICROGEN_FUNCTION_DATA }}" MICROGEN_ACCESS_TOKEN="${{ secrets.MICROGEN_ACCESS_TOKEN }}" MICROGEN_RERUN_DATA="${{ secrets.MICROGEN_RERUN_DATA }}" node ./.github/scripts/deploy.js
